### ISSUE TITLE
[Questions] Change blue tone

### ISSUE THREAD

**Issue by ErSpieltHD** [arichorn/uYouPlusExtra#8]
The blue tone is really hard to read (in dark mode). Please change it to an actual blue. my hex color is #0978B8

p.s. im not colorblind

**Comment by arichorn** [comment]
Nice! but you got one for light mode? There’s a reason why there’s two colors so it’ll work natively with light/dark mode.

**Comment by arichorn** [comment]
https://github.com/arichorn/uYouPlusExtra/releases/tag/v17.46.4-2.1-(412)
this is a temporary release, but this uses the New Blue Dark Theme
but the blue Light Theme is unchanged.
And just so you know this is a temporary release. It’s like that since it’s currently unpolished with the new tweak I implemented.

**Comment by arichorn** [comment]
![04E43BA3-3EB0-41DD-BF69-D396FD50DE55](https://user-images.githubusercontent.com/78001398/204686247-33099d51-6beb-44ad-bdea-6627f9a79f88.jpeg)
Here’s the new Blue Tone in Dark Mode

**Comment by arichorn** [comment]
I Released it 😅
Enjoy!
